version: "3.8"

services:
  user-postgres:
    container_name: fyle-user-postgres
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: userDB
    volumes:
      - user-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  metadata-postgres:
    container_name: fyle-metadata-postgres
    image: postgres
    hostname: localhost
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: metadataDB
    volumes:
      - metadata-postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  server:
    build:
      context: .
      dockerfile: cmd/server/Dockerfile
    container_name: fyle-server
    ports:
      - "3000:3000"
    working_dir: /app
    environment:
      - GO_ENV=development
    depends_on:
      - user-postgres
      - metadata-postgres
    volumes:
      - ./:/app

volumes:
  user-postgres-data:
  metadata-postgres-data:
